name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21d
        
    - name: Get fyne
      run: go get github.com/fyne-io/fyne
      
    - name: Get fyne-cross
      run: go get github.com/fyne-io/fyne-cross
      
    - name: Build linux
      run: fyne-cross linux
    - name: Build windows
      run: fyne-cross windows
    - name: Build darwin
      run: fyne-cross darwin
    
    - name: Build android
      run: ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }} fyne package -os android -appID cn.edu.bupt.sdmda.tranclient -name TranClient -icon Icon.png 
    - name: Upload linux binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/tranhost-client/tranhost-client/fyne-cross/dist/linux-amd64/tranhost-client.tar.gz
        asset_name: tranhost-client.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
    - name: Upload windows binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/tranhost-client/tranhost-client/fyne-cross/dist/windows-amd64/tranhost-client.exe.zip
        asset_name: tranhost-client.exe.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
    - name: Zip app folder for darwin release
      run: zip -q -r /home/runner/work/tranhost-client/tranhost-client/fyne-cross/dist/darwin-amd64/tranhost-client.app.zip /home/runner/work/tranhost-client/tranhost-client/fyne-cross/dist/darwin-amd64/tranhost-client.app
    - name: Upload darwin binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/tranhost-client/tranhost-client/fyne-cross/dist/darwin-amd64/tranhost-client.app.zip
        asset_name: tranhost-client.app.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
    - name: Upload android package to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/tranhost-client/tranhost-client/TranHost.apk
        asset_name: TranHost.apk
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Get fyne
      run: go get github.com/fyne-io/fyne
      
    - name: Get fyne-cross
      run: go get github.com/fyne-io/fyne-cross
      
    - name: Build ios
      run: fyne package -os ios -appID cn.edu.bupt.sdmda.tranclient -name TranClient -icon Icon.png 
 
    - name: Upload ios package to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/tranhost-client/tranhost-client/TranHost.app
        asset_name: TranHost.app
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
