name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    
    - name: Get fyne-cross
      run: go get github.com/fyne-io/fyne-cross
      
    - name: Build linux
      run: fyne-cross linux
    - name: Build windows
      run: fyne-cross windows
    - name: Build darwin
      run: fyne-cross darwin
    - name: Upload linux binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/tranhost-client/tranhost-client/fyne-cross/dist/linux-amd64/tranhost-client.tar.gz
        asset_name: tranhost-client.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
    - name: Upload windows binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/tranhost-client/tranhost-client/fyne-cross/dist/windows-amd64/tranhost-client.exe.zip
        asset_name: tranhost-client.exe.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
    - name: Upload darwin binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/tranhost-client/tranhost-client/fyne-cross/dist/darwin-amd64/tranhost-client.app
        asset_name: tranhost-client.app
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
